---
title: "mauricer demo"
author: "Richèl J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mauricer demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r}
library(mauricer)
library(testthat)
```

```{r}
if (!has_internet()) {
  print("No internet connection")
}
```

List all BEAST2 packages:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  beast2_packages <- get_beast2_pkg_names() 
  knitr::kable(head(beast2_packages))
}
```

Find a package that is not installed:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  first_absent_package_name <- beast2_packages[ 
    beast2_packages$installed_version == "NA", 
  ]$name[1]
  print(first_absent_package_name)
}
```

Check that is indeed not installed:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  expect_false(is_beast2_pkg_installed(first_absent_package_name))
}
```

Install that package:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  install_beast2_pkg(first_absent_package_name)
}
```

Should not be the first absent package anymore:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  beast2_packages <- get_beast2_pkg_names() 
  new_first_absent_package_name <- beast2_packages[ 
   beast2_packages$installed_version == "NA", 
  ]$name[1]
  expect_true(new_first_absent_package_name != first_absent_package_name)
}
```

Uninstall that package:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  uninstall_beast2_pkg(first_absent_package_name)
}
```

Should be the first absent package again:

```{r}
if (has_internet() && beastier::is_beast2_installed()) {
  beast2_packages <- get_beast2_pkg_names() 
  last_first_absent_package_name <- beast2_packages[ 
   beast2_packages$installed_version == "NA", 
  ]$name[1]
  expect_equal(last_first_absent_package_name, first_absent_package_name)
}
```
